language: node_js
node_js:
  - 8.11.2
  - '9'
services:
  - docker
before_install:
  - 'git config --global url."git@github.com:".insteadOf "https://github.com/"'
  - npm install -g lsc nsp
  - docker build -t services-cache ./run
  - 'docker run -d -p 6379:6379 services-cache'
install:
  - npm install
script:
  - nsp check
  - npm run coverage
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage;
cache:
  directories:
    - ~/.npm
notifications:
  email: false
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
